---
fbm: &filter_branch_develop
  when:
    branch:
      - develop
      - master
    event:
      exclude:
        - pull_request
fbm: &filter_branch_master
  when:
    branch:
      - master
    event:
      exclude:
        - pull_request

kind: pipeline
name: default

concurrency:
  limit: 1

platform:
  os: linux
  arch: amd64


build:
  image: 3.3.9-jdk-7
  pull: true
  commands:
    - mvn clean
    - mvn install

#steps:
#  - name: build-maven
#    user: root
#    pull: always
#    image: maven
#    command:
#      - mvn clean install