kind: pipeline
name: pipeline-example-maven

steps:
  - name: build-maven
    image: maven:3.6.3-jdk-8
    volumes:
      - name: cache
        path: /root/.m2
    commands:
      - pwd
      - ls -l
      - mvn clean install