package hello;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class MainService {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ParticipanteRepository userRepository;

    public synchronized Participante execute(String nome){
        System.out.println("Começou");
        // This returns a JSON or XML with the users
        String s = nome.split("&")[0].split("=")[1];
        Participante atual = userRepository.findById(Integer.parseInt(s)).get();
        if( "nao".equalsIgnoreCase(atual.getJaretirou())) {
            userRepository.updateJaRetirou(Integer.parseInt(s));
            Participante achou = userRepository.findRandom(Integer.parseInt(s));
            userRepository.updateFoiRetirado(achou.getId());
            System.out.println("Terminou");
            return achou;
        }else{
            Participante p = new Participante();
            p.setFirstname("Você já retirou alguém ... tente se lembrar ...");
            System.out.println("Terminou");
            return p;
        }
    }
}
