package hello;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import javax.transaction.Transactional;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private ParticipanteRepository userRepository;

	@Autowired MainService mainService;

	@PostMapping(path="/all")
	public @ResponseBody
	Iterable<Participante> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAllNaoRetirou();
	}

	@PostMapping(path="/findById")
	public @ResponseBody
	Participante getAllUsers(@RequestBody String nome) {
		return mainService.execute(nome);
	}
}
